
replicaCount: 2

namespace: akash-ns

image:
  repository: 16akash/streetfood-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 2000

containerPort: 2000

config:
  APP_NAME: IndianStreetFood
  APP_PORT: "2000"
  APP_MODE: production

secret:
  DB_USER: admin
  DB_PASSWORD: admin123

